stages:
  - build
  - test

before_script:
  - apt-get update && apt-get install -y gcc git make libcunit1 libcunit1-doc libcunit1-dev

build_job:
  stage: build
  script:
    - make build

test_job:
  stage: test
  script:
    - make cunits
  dependencies:
    - build_job
